module.exports = [
	{
		name: 'editor',
		sections: [
			{
				title: 'Editor',
				items: [
					'/editor-docs/',
					'/editor-docs/features/',
					'/editor-docs/team/',
					'/editor-docs/getting-started/',
					'/editor-docs/faq/',
					'/editor-docs/no-cache/',
				],
			},
			{
				title: 'Other',
				items: ['/editor-docs/other/molang/'],
			},
		],
	},
	{
		name: 'extensions',
		sections: [
			{
				title: 'General',
				items: [
					'/extension-docs/',
					'/extension-docs/contributing/',
					'/extension-docs/other/default-file-types/',
					'/extension-docs/compiler-plugins/',
					'/extension-docs/custom-molang/',
					'/extension-docs/custom-commands/',
					'/extension-docs/custom-components/',
					'/extension-docs/json/file-definitions/',
					'/extension-docs/json/lightning-cache/',
					'/extension-docs/json/presets/',
					'/extension-docs/json/themes/',
				],
			},
			{
				title: 'Extension Modules',
				items: [
					'/extension-docs/scripts/index/',
					'/extension-docs/scripts/modules/bridge-com-mojang/',
					'/extension-docs/scripts/modules/bridge-compare-version/',
					'/extension-docs/scripts/modules/bridge-env/',
					'/extension-docs/scripts/modules/bridge-fetch-definition/',
					'/extension-docs/scripts/modules/bridge-file-importer/',
					'/extension-docs/scripts/modules/bridge-fs/',
					'/extension-docs/scripts/modules/bridge-globals/',
					'/extension-docs/scripts/modules/bridge-json5/',
					'/extension-docs/scripts/modules/bridge-monaco/',
					'/extension-docs/scripts/modules/bridge-notifications/',
					'/extension-docs/scripts/modules/bridge-path/',
					'/extension-docs/scripts/modules/bridge-sidebar/',
					'/extension-docs/scripts/modules/bridge-tab/',
					'/extension-docs/scripts/modules/bridge-tab-actions/',
					'/extension-docs/scripts/modules/bridge-theme/',
					'/extension-docs/scripts/modules/bridge-toolbar/',
					'/extension-docs/scripts/modules/bridge-ui/',
					'/extension-docs/scripts/modules/bridge-utils/',
					'/extension-docs/scripts/modules/bridge-windows/',
					'/extension-docs/scripts/interfaces/builtin/',
					'/extension-docs/scripts/interfaces/idisposable/',
					'/extension-docs/scripts/interfaces/igethandleconfig/',
					'/extension-docs/scripts/interfaces/imkdirconfig/',
					'/extension-docs/scripts/interfaces/inotificationconfig/',
					'/extension-docs/scripts/interfaces/isidebarconfig/',
					'/extension-docs/scripts/interfaces/itabactionconfig/',
					'/extension-docs/scripts/interfaces/itabpreviewconfig/',
					'/extension-docs/scripts/interfaces/sidebarelement/',
					'/extension-docs/scripts/interfaces/signal/',
				],
			},
		],
	},
]
